import { StyleSheet, Dimensions } from "react-native";

const screenWidth = Dimensions.get("window").width;

export const globalStyles = StyleSheet.create({
  // === সার্বিক ও কন্টেইনার স্টাইল ===
  container: { flex: 1, backgroundColor: "#f8fafc" },
  scrollView: { flex: 1 },

  // === মডাল স্টাইলসমূহ ===
  modalOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    zIndex: 50,
    justifyContent: "center",
    alignItems: "center",
    padding: 16,
  },
  modalCard: {
    backgroundColor: "#ffffff",
    borderRadius: 32,
    padding: 24,
    width: "100%",
    maxWidth: 340,
    alignItems: "center",
    elevation: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 12 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
  },
  logoContainer: {
    width: 80,
    height: 80,
    backgroundColor: "#f1f5f9",
    borderRadius: 40,
    alignItems: "center",
    justifyContent: "center",
    marginBottom: 16,
  },
  logoText: { fontSize: 40 },
  modalTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#1e293b",
    textAlign: "center",
  },
  modalSubtitle: {
    fontSize: 13,
    color: "#64748b",
    marginTop: 6,
    textAlign: "center",
    marginBottom: 24,
  },
  form: { width: "100%" },
  inputLabel: {
    fontSize: 13,
    fontWeight: "700",
    color: "#475569",
    marginBottom: 6,
    paddingLeft: 2,
  },
  formInput: {
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 16,
    paddingHorizontal: 14,
    paddingVertical: 12,
    fontSize: 15,
    color: "#1e293b",
    marginBottom: 16,
    width: "100%",
  },
  submitButton: {
    backgroundColor: "#059669",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 14,
    borderRadius: 16,
    marginTop: 10,
    width: "100%",
    elevation: 3,
    shadowColor: "#059669",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
  },
  submitButtonText: { color: "#ffffff", fontSize: 15, fontWeight: "bold" },

  // === হেডার ও নোটিশ বোর্ড স্টাইলসমূহ ===
  headerContainer: {
    backgroundColor: "#059669",
    paddingTop: 25,
    paddingBottom: 35,
    paddingHorizontal: 20,
    borderBottomLeftRadius: 28,
    borderBottomRightRadius: 28,
    alignItems: "center",
    elevation: 5,
  },
  subTitle: {
    color: "#a7f3d0",
    fontSize: 13,
    fontWeight: "600",
    marginBottom: 6,
  },
  mainTitle: {
    color: "#ffffff",
    fontSize: 22,
    fontWeight: "bold",
    textAlign: "center",
    marginBottom: 14,
  },
  badge: {
    backgroundColor: "rgba(255, 255, 255, 0.22)",
    paddingVertical: 6,
    paddingHorizontal: 18,
    borderRadius: 50,
  },
  badgeText: { color: "#ffffff", fontSize: 13, fontWeight: "700" },

  noticeContainer: {
    flexDirection: "row",
    backgroundColor: "#fef2f2",
    borderBottomWidth: 1,
    borderBottomColor: "#fee2e2",
    alignItems: "center",
    height: 40,
    overflow: "hidden",
  },
  noticeLabel: {
    backgroundColor: "#ef4444",
    paddingHorizontal: 12,
    height: "100%",
    justifyContent: "center",
    zIndex: 10,
  },
  noticeLabelText: { color: "#ffffff", fontSize: 12, fontWeight: "bold" },
  noticeScrollArea: { flex: 1, justifyContent: "center", width: "100%" },
  noticeText: { color: "#dc2626", fontSize: 13, fontWeight: "600", width: 900 },

  // === সার্চ বার স্টাইলসমূহ ===
  searchSection: { paddingHorizontal: 20, marginTop: -20, zIndex: 1 },
  searchContainer: {
    flexDirection: "row",
    backgroundColor: "#ffffff",
    alignItems: "center",
    paddingHorizontal: 15,
    borderRadius: 16,
    height: 54,
    elevation: 3,
  },
  searchIcon: { marginRight: 10 },
  input: { flex: 1, color: "#1e293b", fontSize: 15 },

  // === গ্রিড ও ক্যাটাগরি সেকশন ===
  gridSection: { paddingHorizontal: 20, marginTop: 25 },
  sectionTitle: {
    fontSize: 17,
    fontWeight: "bold",
    color: "#1e293b",
    marginBottom: 15,
    paddingLeft: 2,
  },
  gridContainer: {
    flexDirection: "row",
    flexWrap: "wrap",
    justifyContent: "space-between",
  },
  gridCard: {
    backgroundColor: "#ffffff",
    width: "48%",
    borderRadius: 20,
    paddingVertical: 18,
    paddingHorizontal: 12,
    alignItems: "center",
    marginBottom: 12,
    elevation: 1,
  },
  iconContainer: {
    width: 50,
    height: 50,
    borderRadius: 50,
    alignItems: "center",
    marginBottom: 10,
    justifyContent: "center",
  },
  cardTitle: {
    fontSize: 13,
    fontWeight: "600",
    color: "#334155",
    textAlign: "center",
  },

  // === কন্টাক্ট লিস্ট ও কার্ড স্টাইলসমূহ ===
  listSection: { paddingHorizontal: 20, marginTop: 20 },
  contactCard: {
    backgroundColor: "#ffffff",
    borderRadius: 16,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
    elevation: 1,
  },
  contactInfo: { flex: 1, marginRight: 10 },
  contactName: {
    fontSize: 15,
    fontWeight: "bold",
    color: "#1e293b",
    marginBottom: 4,
  },
  contactPhone: { fontSize: 14, fontWeight: "600", marginBottom: 2 },
  contactSub: { fontSize: 12, color: "#64748b" },
  callButton: {
    flexDirection: "row",
    alignItems: "center",
    paddingVertical: 10,
    paddingHorizontal: 14,
    borderRadius: 12,
  },
  callButtonText: {
    color: "#ffffff",
    fontSize: 13,
    fontWeight: "700",
    marginLeft: 6,
  },
  emptyText: {
    color: "#94a3b8",
    fontSize: 14,
    textAlign: "center",
    marginTop: 20,
  },

  // === ডিটেইলস ও সাব-স্ক্রিন হেডার ===
  detailsHeader: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    paddingHorizontal: 15,
    paddingTop: 15,
    paddingBottom: 15,
    elevation: 4,
  },
  backButton: { padding: 5 },
  detailsHeaderTitle: { color: "#ffffff", fontSize: 18, fontWeight: "bold" },
  filterWrapper: {
    backgroundColor: "#ffffff",
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: "#e2e8f0",
  },
  filterScroll: { paddingHorizontal: 15, gap: 8 },
  filterChip: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 50,
    alignItems: "center",
    justifyContent: "center",
  },
  filterChipText: { fontSize: 13, fontWeight: "700" },
  badgeContainer: {
    marginLeft: 8,
    paddingHorizontal: 8,
    paddingVertical: 2,
    borderRadius: 6,
    marginTop: 2,
  },
  badgeTextStyled: { fontSize: 11, fontWeight: "bold" },

  // === অভিযোগ ফরম স্টাইলসমূহ ===
  formCard: {
    backgroundColor: "#ffffff",
    borderRadius: 20,
    padding: 20,
    elevation: 2,
    marginBottom: 20,
  },
  formInstruction: {
    fontSize: 14,
    color: "#475569",
    lineHeight: 22,
    marginBottom: 20,
    textAlign: "center",
  },
  complaintInputLabel: {
    fontSize: 14,
    fontWeight: "700",
    color: "#1e293b",
    marginBottom: 8,
    paddingLeft: 2,
  },
  complaintFormInput: {
    backgroundColor: "#f8fafc",
    borderWidth: 1,
    borderColor: "#e2e8f0",
    borderRadius: 12,
    paddingHorizontal: 14,
    paddingVertical: 10,
    fontSize: 15,
    color: "#1e293b",
    marginBottom: 18,
  },
  complaintSubmitButton: {
    backgroundColor: "#a855f7",
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    paddingVertical: 14,
    borderRadius: 14,
    marginTop: 10,
    elevation: 2,
  },
  complaintSubmitButtonText: {
    color: "#ffffff",
    fontSize: 15,
    fontWeight: "bold",
    marginLeft: 8,
  },
});
